export const tests = [
  {
    word: 'hospital',
    words: [
      'output',
      'moral',
      'save',
      'coup',
      'garlic',
      'real',
      'hospital',
      'echo',
      'earthquake',
      'model',
      'comprehensive',
      'crusade',
      'firefighter',
      'union',
      'visible',
      'strength',
      'short',
      'language',
      'professor',
      'inspire',
      'bell',
      'heavy',
      'carriage',
      'pair',
      'soak',
      'clerk',
      'wording',
      'flexible',
      'hit',
      'chocolate',
      'deadly',
      'mail',
      'sock',
      'maid',
      'perform',
      'bubble',
      'organize',
      'cake',
      'surprise',
      'leadership',
      'future',
      'elegant',
      'blade',
      'business',
      'organization',
      'strange',
      'handy',
      'honest',
      'entry',
      'notorious',
      'acquaintance',
      'shiver',
      'syndrome',
      'navy',
      'coast',
      'east',
      'genetic',
      'thanks',
      'mixture',
      'electronics',
      'limit',
      'beer',
      'abridge',
      'achieve',
      'attachment',
      'road',
      'soul',
      'dealer',
      'step',
      'cooperate',
      'spirit',
      'node',
      'mug',
      'pull',
      'funeral',
      'recycle',
      'sausage',
      'hardware',
      'advance',
      'knit',
      'impound',
      'discount',
      'traction',
      'cell',
      'subject',
      'structure',
      'bomb',
      'turkey',
      'abolish',
      'precede',
      'reliance',
      'grateful',
      'feed',
      'eliminate',
      'bad',
      'ready',
      'beginning',
      'computer',
      'center',
      'lease',
    ],
  },
  {
    word: 'bubble',
    words: [],
  },
  {
    word: 'road',
    words: [],
  },
  {
    word: 'recycle',
    words: [],
  },
  {
    word: 'shiver',
    words: [],
  },
  {
    word: 'grateful',
    words: [],
  },
  {
    word: 'bell',
    words: [],
  },
  {
    word: 'thanks',
    words: [],
  },
  {
    word: 'hardware',
    words: [],
  },
  {
    word: 'beginning',
    words: [],
  },
];
